### ISSUE TITLE
Update architecture list for ros-melodic-cpp

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-roscpp#2]

**Comment by bionade24** [comment]
Why shouldn't we provide any? I build on i686, amd64, armhf and arm64, everything worked. I hate the AUR maintainers which do this for no reason, like `console-bridge` (I'm not sure if I remember correctly). You always have to edit to make it arm compatible.

**Comment by acxz** [comment]
I think the reason is that if the compiled package is architecture specific, then we need to specify which architectures. 
Here is what the Arch Wiki says:
https://wiki.archlinux.org/index.php/Arch_package_guidelines#Architectures

**Comment by bionade24** [comment]
Ok, I tought this would be done by automatically by makepkg. Will build it into the PKGBUILD generator tomorrow, so packages that use cmake have `i686, x86_64, armhf and arm64` in the array.
Edit: `arch=('i686' 'x86_64' 'aarch64' 'armv7h' 'armv6h')`

**Comment by acxz** [comment]
Sweet thx!

**Comment by acxz** [comment]
@bionade24 Should we also add `arm`? https://wiki.archlinux.org/index.php/PKGBUILD#arch

Also what is the status of this currently?

**Comment by bionade24** [comment]
`armv5` is older than the pi1, no one should even try building ROS on it, all processors probably have >=500Mhz, so no. 
Status: As I now have to rebuild my private Repo because of the boost updates, I'll updates everything with @jwhendy script I fixed & refactored to fit  better. I'm currently not finished with this because I not even just want to correct the arch array, I also want to add tests.

**Comment by bionade24** [comment]
I currently struggle with adding tests. Do you have an idea? https://discourse.ros.org/t/who-is-using-ros-on-archlinux/388/29

**Comment by acxz** [comment]
Sadly, I am actually not familiar with tests in ROS.

**Comment by jwhendy** [comment]
Same here (no experience at all).

Also, finally recovering from not 1, not 2, but 3 hard drive issues so I haven't done much of anything on ROS in a while as I got that sorted. @bionade24 per our earlier btrfs discussion, I suspect it could have been related to continuous trim after all (`discard` in `fstab` and `luks.options`) or a kernel clash with respect to samsung 850 ssds dm-crypt. If you want to read the saga, [here it is](https://lore.kernel.org/linux-btrfs/CA+M2ft9ANwKT1+ENS6-w9HLtdx0MDOiVhi5RWKLucaT_WtZLkg@mail.gmail.com/). My newer nvme is saved and healed but my SSD (5yrs old) is likely not recoverable.

**Comment by bionade24** [comment]
I read it. As the 850's problem should not have been occured on the nvme and the cache is changing a lot, I think it's really somehow caused by bugs in the continious TRIM feature. I future you probably should scrub regularly and maybe as a nicer backup solution you could export the subvolumes directly, btrbackup is a nice script for this task.

I'll investigate further how test can be done in plain cmake, but for now I'll simply will fix the arch arrays.

**Comment by bionade24** [comment]
As I have to rebuild every package because of the boost updates, I finally got myself to do this, everything containing c++ code should now have a correct arch array. Maybe me detection method is really bad, but I didn't want to extract and parse the `CMakeLists.txt` out of every package. Sorry additionally for not mention the deletion of the unnecessary python flags. If you find any packages where my script handled wrong, please open issues. 
About arch4edu: @acxz Could you maybe wait with doing this? As gmock still links against python2 and the maintainer felix is much to busy, I'll try to become a TU(I should already have enough TUs that will suggest me). So additionally to the gtest packages I'll try to get at least `ros-melodic-desktop` and its dependencies into community repo, so that the core stack is dowlodable without discovering arch4edu.

**Comment by acxz** [comment]
That's great! Great work on this man, you are really killing it!
Yeah if we can get into the community repo that would be much better!
Can you post a link to where your script is? Sorry but I can't seem to find it.
And yeah for sure, you know I will be testing the build process left and right. Def not afraid to post issues lol.
Congrats man, can't wait to rebuild ROS once the updated PKGBUILDS get onto the AUR.

**Comment by bionade24** [comment]
[Here](https://github.com/bionade24/aur-ci/tree/master/scripts) they are. As I already warned you, they're shitty. ;)

**Comment by acxz** [comment]
No no, not bad man.
When/how long do you think these changes will be reflected in the AUR? I assume they have to go through your build process?

One thing I can see is that some packages (these in fact https://github.com/ros-melodic-arch/ros-melodic-desktop-full/issues/8) do rely on those CMake flags. But we can resolve those once we run into them.

**Comment by bionade24** [comment]
Yes, builds are ongoing, some things should already be compiled/pushed.  Afterwards completing this my binary repo should work with latest boost, too.
